# Build Docker image and push it to docker hub

name: Dockerize amd64

on:
  workflow_dispatch:
    inputs:
      docker_tag:
        description: "Enter KM version (for docker tag)"
        required: true
        default: "0.000.000000.0"

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    env:
      DOCKER_TARGET_PLATFORM: linux/amd64
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build --push --platform linux/amd64 \
            --build-arg BUILD_IMAGE_TAG=9.0-noble-amd64 \
            --build-arg RUN_IMAGE_TAG=9.0-alpine-amd64 \
            --tag "${{ vars.DOCKERHUB_USERNAME }}/service:${{ github.event.inputs.docker_tag }}-amd64" .
